# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

id: org.kde.CrowTranslate
branch: master
sdk: org.kde.Sdk
runtime: org.kde.Platform
runtime-version: 5.15-23.08
tags: ['nightly']
desktop-file-name-suffix: " (Nightly)"
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --socket=pulseaudio
  - --share=network
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
copy-icon: true
command: crow
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/pkgconfig
modules:
  - name: crow-translate
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: .
    modules:
      - name: tesseract
        buildsystem: cmake-ninja
        builddir: true
        config-opts:
          - -DBUILD_SHARED_LIBS:BOOL=ON
        cleanup:
          - /bin
        sources:
          - type: archive
            url: https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.4.1.tar.gz
            sha256: c4bc2a81c12a472f445b7c2fb4705a08bd643ef467f51ec84f0e148bd368051b
        modules:
          - name: leptonica
            buildsystem: cmake-ninja
            builddir: true
            config-opts:
              - -DBUILD_SHARED_LIBS:BOOL=ON
            sources:
              - type: archive
                url: https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.84.1.tar.gz
                sha256: ecd7a868403b3963c4e33623595d77f2c87667e2cfdd9b370f87729192061bef
