variables:
  GIT_SUBMODULE_STRATEGY: recursive
include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-windows-x86-64.yml
      - /gitlab-templates/craft-macos-x86-64.yml
      - /gitlab-templates/craft-appimage.yml
