# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/kwayland': '@stable'

Options:
  cmake-options: '-D WITH_PORTABLE_MODE=ON -D CMAKE_COMPILE_WARNING_AS_ERROR=ON'
  cppcheck-arguments: '--enable=warning,style,performance --suppress=shadowFunction'
  cppcheck-ignore-files: ['src/3rdparty']
  run-tests: False
  setup-x-environment: False
  setup-dbus-session: False
  run-gcovr: False
